import type { NextPage } from "next";
import Head from "next/head";
import { TableRow } from "../components/TableRow";
import { useMonthlyBudget } from "../hooks/useMonthlyBudget";

const Home: NextPage = () => {
  const { monthlyBudget } = useMonthlyBudget(8);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full justify-center">
        <div className="flex flex-col w-3/4">
          <div className="flex h-40"></div>
          <div className="rounded-t-lg flex w-full bg-blue-200 p-2">
            <ColumnHeader name="Date" />
            <ColumnHeader name="Running Total" />
            <ColumnHeader name="Total Transactions" />
            <ColumnHeader name="Transactions" />
          </div>
          <div>
            {monthlyBudget &&
              monthlyBudget.days.map((day) => (
                <TableRow
                  key={day.id}
                  id={day.id}
                  day={day.day}
                  recurringTransactions={day.transactions.recurringTransactions}
                  runningTotal={day.runningTotal.amount}
                  totalTransactions={day.transactions.total}
                ></TableRow>
              ))}
          </div>
        </div>
      </main>
    </>
  );
};

const ColumnHeader: React.FC<{ name: string }> = (props) => {
  return <div className="p-2 flex-1 text-blue-800 font-bold">{props.name}</div>;
};
export default Home;
