import type { NextPage } from "next";
import Head from "next/head";
import { TableRow } from "../components/TableRow";
import { BudgetDayDetail } from "../models/BudgetDayDetail";
import { getBudgetDaysData } from "../utils/budgetDataUtils";

const Home: NextPage = () => {
  const budgetDays: BudgetDayDetail[] = getBudgetDaysData();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full justify-center">
        <div className="flex flex-col w-3/4">
          <div className="flex h-40"></div>
          <div className="rounded-t-lg flex w-full bg-blue-200 p-2">
            <ColumnHeader name="Date" />
            <ColumnHeader name="Running Total" />
            <ColumnHeader name="Transactions" />
            <ColumnHeader name="Recurring Transactions" />
          </div>
          <div>
            {budgetDays.map((day) => (
              <TableRow
                key={day.date.toDateString()}
                date={day.date}
                recurringTransactions={day.recurringTransactions}
                runningTotal={day.runningTotal}
                transactions={day.transactions}
              ></TableRow>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

const ColumnHeader: React.FC<{ name: string }> = (props) => {
  return <div className="p-2 flex-1 text-blue-800 font-bold">{props.name}</div>;
};
export default Home;
